# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-01 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0003_add_follow_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='context_message',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='action',
            name='primary_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='action',
            name='secondary_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='action',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
